stages:
  - sync
  - test
  - coverage
  - build
  - deploy

image: python:3.10

# A exécuter avant chaque job
before_script:
  - pip install --upgrade pip
  - pip install hatch hatch-vcs

# Job pour exécuter les tests unitaires et collecter la couverture
test:
  stage: test
  script:
    - hatch run pip install pytest pytest-cov
    - hatch run pytest --cov=src --cov-report=xml
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

build:
  stage: build
  script:
    - echo "my_arithmetic-sondos-kocila deployment on stable servers"
    - hatch build
    - ls -l dist/
    - rm -rf dist/
  only:
    - tags

deploy:
  stage: deploy
  script:
    - echo "my_arithmetic-sondos-kocila deployment on stable servers"
    - hatch build
    - ls -l dist/
    - rm -rf dist/
  only:
    - tags

sync-with-github:
  stage: sync
  before_script:
    - git config --global pull.ff only
  script:
    - git remote -v | grep -w github || git remote add github $REMOTE_REPOSITORY_URL
    - git remote set-url github $REMOTE_REPOSITORY_URL
    - git checkout main
    - echo "Pulling updates from origin main..."
    - git pull origin main --rebase
    - echo "Pulling updates from GitHub main..."
    - git pull github main --rebase
    - echo "Pushing changes to GitHub..."
    - git push $REMOTE_REPOSITORY_URL HEAD:main --force
    - git push $REMOTE_REPOSITORY_URL --tags
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'