stages:
  - build
  - test
  - coverage

image: python:3.10

# A exécuter avant chaque job
before_script:
  - pip install --upgrade pip
  - pip install hatch hatch-vcs

# Job pour la construction du projet 
build:
  stage: build
  script:
    - hatch build
    - ls -l dist/
    - rm -rf dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Job pour exécuter les tests unitaires et collecter la couverture
test:
  stage: test
  script:
    - hatch run pip install pytest pytest-cov
    - hatch run pytest --cov=src --cov-report=xml
  artifacts:
    paths:
      - coverage.xml  # pour que je puisse récupérer un rapport de couverture généré par Hatch
    expire_in: 1 week
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)%$/'
