name: Build Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Hatch
        run: pip install hatch hatch-vcs

      - name: Build project
        run: |
          hatch build
          mkdir -p artifacts
          cp -r dist/ artifacts/
          rm -rf dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/